### ISSUE TITLE
Support for signing raw bytes on Ledger Filecoin app

### ISSUE THREAD

**Issue by simonkim0515** [Zondax/ledger-filecoin#118]
Today the ledger Filecoin app lets you sign messages that results in a transaction that is sent on the Filecoin chain. The ledger Filecoin app needs support signing raw bytes or messages that do not end up on chain, examples include: 

- `lotus wallet sign`: to sign arbitrary bytes and prove ownership of a private key
- `lotus filplus sign-remove-data-cap-proposal`: for notaries to sign proposal to remove datacap from client addresses
- `lotus client deal`: kick off deal proposal to store data on Filecoin network as a outlined in #86 

As written today here: https://github.com/Zondax/ledger-filecoin/blob/main/app/src/apdu_handler.c#L193, it only supports signing transaction message (it parses the message, decode using CBOR decoder and render it on the ledger device screen). If we feed it with raw bytes, parsing logic will fail. To support the above scenarios, we need the app to support signing raw bytes with the ledger device. 

:link: [zboto Link](https://app.clickup.com/t/85zrqw13t)

**Comment by eshon** [comment]
Some additional notes on this from Zondax…

- Cannot sign raw bytes as raw bytes - but mostly text
- This needs a RAW prefix - so there is no chance it can be a transfer - so user doesn’t sign a transfer by mistake that looks like raw bytes
- with Cosmos - users started misusing this and signing large PDFs (e.g. to prove their identity, etc.) and this went in weird directions
   - Many teams want to sign WASM, but those are multi-MB
- So FYI - with this **users will NEVER will able to sign more than 1 MB** (otherwise it's insecure and slow - 10-15min/MB with no revisions)

**Comment by neithanmo** [comment]
is there an agreement on what the raw prefix would look like?
for example, Ethereum has a signMessage feature with a "raw" prefix like:
`\x19Ethereum Signed Message:\n32"`
where:
- \x19 is just an arbitrary value used as a header prefix to avoid collisions let's say with transaction types or so.
- 32: the length of the remaining raw bytes. this could be a variant-like encoded value or in FIL it could be a cbor encoded length indicating the actual raw bytes to sign in bytes.  however, if we agree on signing/reviewing a hash, this value is not necessary.

**Comment by neithanmo** [comment]
Tracking:

- [ ] remove-datacap-proposal via #127 
- [ ] client deal
- [ ]  sign raw-bytes
