### ISSUE TITLE
Secp256k1 signature format

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-filecoin#30]
Lotus expect secp256k1 signatures to be in RSV format (compressed 65 bytes)

Reference: https://github.com/ipsn/go-secp256k1/blob/9d62b9f0bc52d16160f79bfb84b2bbf0f6276b03/secp256.go#L52-L53

At the moment, we are returning the signature in DER format. To simplify app users, it is better to modify this and return the expected format directly.

**Comment by jinqiao0423** [comment]
Hi, currently I'm learning about Lotus. I observed that currently command 'lotus wallet sign' with a secp256k1(f1) address will return a 66-length signature which is apparently not in RSV format. Could you tell me whether there is a way to get a RSV format signature so that I can verify it in openzeppelin? Thx!

**Comment by ftheirs** [comment]
Hi @jinqiao0423! For signature verification, we are using a 3rd party library that allows us to import a DER signature. The import method will convert that signature into RS format (if I'm not mistaken) and then use it for verification.

You can check it here:
https://github.com/Zondax/ledger-filecoin/blob/65f56bd738b4e55531ad35e7317d2a9d5554e811/tests_zemu/tests/standard.test.ts#L150-L151
